copy D:\HerrUntermoser\svn\player\air\Abstellflaeche1.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Abstellflaeche2.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\airport_1920.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Ankermast_Staaken.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Empfangsgebaeude_Boeblingen.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Empfangsgebaeude_Laage.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Frachthalle_Gera.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\lsh.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Luftdepot_1920.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Postoffice_1920.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Tower_Dortmund.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\air\Tower_Fuhlsbuettel.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\GrosserTank.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Hauptquartier.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Hq7_hta.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Erz.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Holz.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Kohle.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Muell.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Sand.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Schrott.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Stahl.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Kran_Lagerplatz_Steine.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\LS_Grombach.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\LS_Hannover.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Parkplatz.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Portalkran_Holz.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Portalkran_Schrott.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Portalkran_Schuettgut.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\all\Portalkran_Stahl.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\monorail\MonorailDepot.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\monorail\MonorailGround.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\monorail\Monorail_Bahnhof.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\monorail\Monorail_Bahnhof_hoch.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\monorail\Sbahnhof128.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\monorail\Sbahnhof96.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\monorail\schwebebahn_bahnhof.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\ALP_Bahnhof_HG.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\ALP_Bahnhof_NG.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\ALP_PlattformPers.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bahnhof_Dammtor.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bahnhof_Lauingen.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bahnsteig_mit_Glasdach.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bahnsteig_mit_Glasdach_einzeln-SW.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bahnsteig_mit_Glasdach_einzeln_NO.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\bhb.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\bhb2.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bsteig_Ampersand.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bsteig_Ampersand02.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Bsteig_Doppelgleis.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Depot_LS_Rinteln.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Depot_rail.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\DieselTankStelle.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\EG_Bhf_Sonneberg.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\eg_duerrenberg.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\EG_Hochbahn.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Gbahnhof_klein.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Gueter1.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Kohlenbansen-ext.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Kohlenbansen.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Krakow.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Nstbahnsteig.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Plattform.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers2.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers2_einzeln_NO.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers2_einzeln_SW.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers3.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers3_einzeln_NO.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers3_einzeln_SW.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers_einzeln_NO.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\PlattformPers_einzeln_SW.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\SandBahnsteig.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\SiloBhf.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Stellwerk1.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\S_Bahnsteig.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Ubahnhof_Marienplatz.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\VictorianStation.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\Wasserkran.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\rail\WTBW_Heidelberg.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Bushaltestelle_Holzbank.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Bushaltestelle_Holzhaus.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\BusStop.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Containerbruecke_1.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Containerbruecke_2.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Containerbruecke_3.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Containerlager.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Depot_road.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\ISO_Verladung.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Laderampe.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Laderampe2.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Laderampe3.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Laderampe4.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\LKW_Erweiterungen_Bretter.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\LKW_Erweiterungen_holz.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\LKW_Erweiterungen_Schrott.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\LKW_Erweiterungen_Schuettgut1.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\LKW_Erweiterungen_Schuettgut2.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\LKW_Erweiterungen_Stahl.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\PostStop.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\RoadCargoStop.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Rostocker_Tor.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\RR-Bushaltestelle-1993.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\RR-Bushaltestelle_1932.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\RR-Bushaltestelle_1957.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Station_Ladezone.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Station_Oel.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Station_Schuettgut.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\road\Station_Silo.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\tram\mbhk.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\tram\shsbb.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\tram\strassenbahndepot.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\tram\strdnb.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\anleger_alt.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\anleger_altPP.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Anleger_Emden.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Depot_wasser.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Frachthafen.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Frachthafen_klein.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Holzhafen.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Kanal_Frachthalt.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Kanal_Passagierhalt.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Oelhafen.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Passagierterminal.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Postterminal.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\schiffsdepot_alt.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Schuettguthafen.dat D:\HerrUntermoser\pakmaker\testing\
copy D:\HerrUntermoser\svn\player\water\Stueckguthafen.dat D:\HerrUntermoser\pakmaker\testing\