#!/bin/bash

echo "pak96.comic open-source repository compiler for Linux"
echo "====================================================="
echo
echo "This batch compiles this repository into a new folder"
echo "called compiled, makeobj must be in root folder."
echo
echo "Checking for makeobj..."
echo

if [ -e "makeobj" ]; then
    # Create folder for *.paks or delete all old paks if folder already exists
    if [ -d "compiled" ]; then
        rm ./compiled/*.pak
    else
        mkdir compiled
    fi

    echo
    echo "-----------------------------------------------------"
    echo "Compiling air transport..."
    echo "-----------------------------------------------------"
    for d in $(ls -d air/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling city and lanscape..."
    echo "-----------------------------------------------------"
    for d in $(ls -d city-and-landscape/*/ + ls -d city-and-landscape/buildings/*/); dd
        makeobj pak96 ./compiled/ ./$i
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling factories..."
    echo "-----------------------------------------------------"
    makeobj pak96 ./compiled/ ./factory/

    echo
    echo "-----------------------------------------------------"
    echo "Compiling maglevs..."
    echo "-----------------------------------------------------"
    for d in $(ls -d maglev/*/ + ls -d maglev/ways/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling monorails..."
    echo "-----------------------------------------------------"
    for d in $(ls -d monorail/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling others..."
    echo "-----------------------------------------------------"
    for d in $(ls -d other/*/ + ls -d other/powerlines/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling railroad..."
    echo "-----------------------------------------------------"
    for d in $(ls -d rail/*/ + ls -d rail/ways/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling narrowgauge railroad..."
    echo "-----------------------------------------------------"
    for d in $(ls -d rail-narrow/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling road transport..."
    echo "-----------------------------------------------------"
    for d in $(ls -d road/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling trams..."
    echo "-----------------------------------------------------"
    for d in $(ls -d trams/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "-----------------------------------------------------"
    echo "Compiling naval transport..."
    echo "-----------------------------------------------------"
    for d in $(ls -d water/*/ + ls -d water/ways/*/); do
        makeobj pak96 ./compiled/ ./$d
    done

    echo
    echo "====================="
    echo "Compilation Complete!"
    echo "====================="
    echo
else
    echo "ERROR: makeobj not found in root folder."
    exit 1
fi
exit 0